### ISSUE TITLE
wikibase container crashes with Elastic/CirrusSearch error

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-wikibase#46]
During startup of the container via portal-compose:

```
Updating cluster ...
indexing namespaces...
mw_cirrus_metastore missing, creating new metastore index.
Creating metastore index... mw_cirrus_metastore_first   Scanning available plugins...
                experimental-highlighter, extra, ingest-geoip, ingest-user-agent
Elastica\Exception\ResponseException from line 182 of /var/www/html/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php: class java.lang.Boolean cannot be cast to class java.util.Map (java.lang.Boolean and java.util.Map are in module java.base of loader 'bootstrap')
#0 /var/www/html/vendor/ruflin/elastica/lib/Elastica/Request.php(194): Elastica\Transport\Http->exec(Object(Elastica\Request), Array)
#1 /var/www/html/vendor/ruflin/elastica/lib/Elastica/Client.php(689): Elastica\Request->send()
#2 /var/www/html/vendor/ruflin/elastica/lib/Elastica/Index.php(571): Elastica\Client->request('mw_cirrus_metas...', 'PUT', Array, Array)
#3 /var/www/html/extensions/CirrusSearch/includes/MetaStore/MetaStoreIndex.php(201): Elastica\Index->request('mw_cirrus_metas...', 'PUT', Array, Array)
#4 /var/www/html/extensions/CirrusSearch/includes/MetaStore/MetaStoreIndex.php(139): CirrusSearch\MetaStore\MetaStoreIndex->createNewIndex()
#5 /var/www/html/extensions/CirrusSearch/includes/Maintenance/Maintenance.php(227): CirrusSearch\MetaStore\MetaStoreIndex->createIfNecessary()
#6 /var/www/html/extensions/CirrusSearch/maintenance/IndexNamespaces.php(40): CirrusSearch\Maintenance\Maintenance->maybeCreateMetastore()
#7 /var/www/html/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php(65): CirrusSearch\Maintenance\IndexNamespaces->execute()
#8 /var/www/html/maintenance/includes/MaintenanceRunner.php(119): CirrusSearch\Maintenance\UpdateSearchIndexConfig->execute()
#9 /var/www/html/maintenance/doMaintenance.php(84): MediaWiki\Maintenance\MaintenanceRunner->run()
#10 /var/www/html/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php(103): require_once('/var/www/html/m...')
#11 {main}
```

likely due to the latest version updates

**Comment by dajuno** [comment]
currently mediawiki is fixed at version 1.38.1, while most extensions use wmf-1.39.0-x (including cirrussearch). Is this *supposed* to work @physikerwelt ? shouldn't we also use mediawiki wmf 1.39?

**Comment by physikerwelt** [comment]
Maybe [wikibase/elasticsearch:6.5.4-wmde.2](https://portainer.portal.mardi4nfdi.de/#!/2/docker/images/wikibase~2Felasticsearch%3A6.5.4-wmde.2) is not compatible with the latest cirrussearch extension?

**Comment by physikerwelt** [comment]
cool can you do a pull request?

**Comment by dajuno** [comment]
I'm on it in portal-compose, just checking if wdqs should be bumped to wmde.6, too
